### ISSUE TITLE
s3/list-objects completely fails all the time now

### ISSUE THREAD

**Issue by sdegutis** [weavejester/clj-aws-s3#83]
``` clojure
=> (s3/list-objects cred bucket)

NoClassDefFoundError Could not initialize class com.amazonaws.ClientConfiguration  com.amazonaws.services.s3.AmazonS3Client.<init> (AmazonS3Client.java:365)
```

Happens on both versions 0.3.3 and 0.3.10 fwiw.

**Comment by sdegutis** [comment]
Also I didn't find this out when the program launched. I discovered it in the middle of a Ring request with this error message that Ring and/or Jetty gave me:

~~~
HTTP ERROR: 500

Problem accessing /admin. Reason:

    Could not initialize class com.amazonaws.ClientConfiguration
Powered by Jetty://
~~~

**Comment by sdegutis** [comment]
Now getting this:

`NoClassDefFoundError Could not initialize class com.amazonaws.ClientConfiguration  com.amazonaws.services.s3.AmazonS3Client.<init> (AmazonS3Client.java:365)`

**Comment by sdegutis** [comment]
Just discovered that this error occurs regardless if I use 0.3.3 or 0.3.10.

**Comment by sdegutis** [comment]
Also:

~~~clj
=> (import com.amazonaws.ClientConfiguration)

NoSuchMethodError com.fasterxml.jackson.core.JsonFactory.requiresPropertyOrdering()Z  com.fasterxml.jackson.databind.ObjectMapper.<init> (ObjectMapper.java:445)
=> (import 'com.amazonaws.ClientConfiguration)

NoClassDefFoundError Could not initialize class com.amazonaws.ClientConfiguration  java.lang.Class.forName0 (Class.java:-2)
=> (import com.amazonaws.ClientConfiguration)

NoClassDefFoundError Could not initialize class com.amazonaws.ClientConfiguration  java.lang.Class.forName0 (Class.java:-2)

~~~

**Comment by sdegutis** [comment]
Okay, found out it was incompatible versions. Datomic includes its own version of `aws-java-sdk` so I just had to exclude that.

BUT, this doesn't fully fix it. Your latest version, 0.3.10 requires com/amazonaws/aws-java-sdk/1.7.5, which gives me this error:

~~~clj
cleancoders.web.main=> (s3/list-objects cred bucket)

NoSuchMethodError com.fasterxml.jackson.core.JsonParser.getValueAsString()Ljava/lang/String;  com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize (StringDeserializer.java:24)
~~~

Whereas downgrading back to 0.3.3 fixes it. No other dependencies of mine use another aws library according to `lein deps :tree` so this is the only one.

**Comment by sdegutis** [comment]
So, now I'm using `[clj-aws-s3 "0.3.3" :exclusions [[commons-codec] [joda-time] [com.fasterxml.jackson.core/jackson-core]]]` which uses `[com.amazonaws/aws-java-sdk "1.3.18"]` and everything is working great once again.

**Comment by sdegutis** [comment]
So I think this bug report is basically that 0.3.10 seems to not work, when my `lein deps :tree` shows that there are no other libs in my code which require `com.amazonaws.aws-java-sdk`.

**Comment by sickill** [comment]
With 0.3.10 when I first try to evaluate `get-object` I get:

    NoSuchMethodError com.fasterxml.jackson.core.JsonFactory.requiresPropertyOrdering()Z  com.fasterxml.jackson.databind.ObjectMapper.<init> (ObjectMapper.java:445)

When I evaluate it for the second time (after getting the above error) I get:

    NoClassDefFoundError Could not initialize class com.amazonaws.internal.config.InternalConfig$Factory  com.amazonaws.ServiceNameFactory.getServiceName (ServiceNameFactory.java:34)

No other lib includes aws-java-sdk in my project.

**Comment by sickill** [comment]
Output of `lein deps :tree` in my project: https://gist.github.com/sickill/edebec48f0880ef2966370894cbcb40d

**Comment by sickill** [comment]
I made 0.3.10 working by doing this:

    [clj-aws-s3 "0.3.10" :exclusions [com.fasterxml.jackson.core/jackson-core com.fasterxml.jackson.core/jackson-annotations]]

Without above exclusions I was getting the following notices with `lein deps :tree`:

```
Possibly confusing dependencies found:
[clj-aws-s3 "0.3.10" :exclusions [joda-time]] -> [com.amazonaws/aws-java-sdk "1.7.5"] -> [com.fasterxml.jackson.core/jackson-core "2.1.1"]
 overrides
[ring-webjars "0.1.1"] -> [org.webjars/webjars-locator "0.27"] -> [com.fasterxml.jackson.core/jackson-databind "2.3.3"] -> [com.fasterxml.jackson.core/jackson-core "2.3.3"]

Consider using these exclusions:
[ring-webjars "0.1.1" :exclusions [com.fasterxml.jackson.core/jackson-core]]

[clj-aws-s3 "0.3.10" :exclusions [joda-time]] -> [com.amazonaws/aws-java-sdk "1.7.5"] -> [com.fasterxml.jackson.core/jackson-annotations "2.1.1"]
 overrides
[ring-webjars "0.1.1"] -> [org.webjars/webjars-locator "0.27"] -> [com.fasterxml.jackson.core/jackson-databind "2.3.3"] -> [com.fasterxml.jackson.core/jackson-annotations "2.3.0"]

Consider using these exclusions:
[ring-webjars "0.1.1" :exclusions [com.fasterxml.jackson.core/jackson-annotations]]
```

To me it looks like `[aws-java-sdk "1.7.5"]` doesn't work well with `[com.fasterxml.jackson.core/jackson-annotations "2.1.1"]` and `[com.fasterxml.jackson.core/jackson-core "2.1.1"]`...

**Comment by raymcdermott** [comment]
+1 on having to do what @sdegutis mentioned after some odd XML errors brought me sniffing around here

**Comment by sdegutis** [comment]
Closing as I no longer use this library. If anyone wants to reopen, feel free.
