### ISSUE TITLE
put-object throw an IllegalArgumentException

### ISSUE THREAD

**Issue by marcvincenti** [weavejester/clj-aws-s3#92]
I have a simple function to post a file in a bucket
```
(defn post-pic
  "Uploads a picture to S3"
  [file]
  (let [{:keys [filename tempfile]} file]
    (s3/put-object cred my-bucket filename  tempfile)))
```

It works like a charm, however, it throws everytime an IllegalArgumentException saying that 

> No implementation of method: :render of protocol: #'compojure.response/Renderable found for class: com.amazonaws.services.s3.model.PutObjectResult

**Comment by weavejester** [comment]
This is because you're passing the return value of the function to Compojure. `post-pic` returns a `PutObjectResult`, and then you're telling Compojure to render it as a HTTP response. Compojure is throwing an error, telling you it has no idea how to do that.
